- name: Provision app servers in public subnet
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: us-west-2
    ami: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (HVM), SSD Volume Type
    instance_type: t2.micro
    key_name: my-key-pair
    subnet_id: subnet-0123456789abcdef0 #run vpc.yml first, copy the id
    sg_name: my-sg-name
    count: 1
    sg_description: "Security group for app servers"
    sg_rules:
      - proto: tcp
        ports:
          - 22
          - 80
          - 443
        cidr_ip: 0.0.0.0/0

  tasks:
    - name: Create security group
      amazon.aws.ec2_group:
        name: "{{ sg_name }}"
        description: "{{ sg_description }}"
        vpc_id: "{{ subnet_id }}"
        region: "{{ region }}"
        rules: "{{ sg_rules }}"
      register: sg

    - name: Launch instances
      amazon.aws.ec2:
        count: "{{ count }}"
        key_name: "{{ key_name }}"
        image: "{{ ami }}"
        instance_type: "{{ instance_type }}"
        vpc_subnet_id: "{{ subnet_id }}"
        group_id: "{{ sg.group_id }}"
        wait: true
        region: "{{ region }}"
        instance_tags:
          Name: "App server {{ item }}"
        exact_count: true
      loop: "{{ range(1, count + 1) | list }}"
