---
- hosts: localhost
  vars:
    region: "us-west-2"
    tag_name: testing
    key_name: testing
    instance_type: t2.micro
    ami_id: ami-0f1a5f5ada0e7da53  # Amazon Linux 2 Kernel 5.10 AMI 2.0.20230207.0 x86_64 HVM gp2
    instance_profile_name: EC2-webserver
    count: 1
    creator: ansible
    group: privateserver # use for group_vars> "xxx.yml"
    ansible_port: 22
    # ec2_volume_size: 16
    # count_tag: testing
    vpc_subnet_id: subnet-0dc6651df1e456d57
  roles:
  - ec2
  
  pre_tasks: 
  - name: example ec2 group
    ec2_group:
       name: testing group
       description: an EC2 group
       vpc_id: vpc-035244768fb238cb1
       region: "{{ region }}"
       rules:
         - proto: tcp
           from_port: 8080 #jenkins
           to_port: 8080
           cidr_ip: 10.0.1.0/24
         - proto: tcp
           from_port: 22 #ssh
           to_port: 22
           cidr_ip: 0.0.0.0/0
    register: create_ec2_sg
    
  - name: "set fact: ec2 sg ID"
    set_fact:
      ec2_sg_id: "{{ create_ec2_sg.group_id }}"

- hosts: privateserver
  become: true
  become_method: sudo
  # connection: ssh
  remote_user: ec2-user
  tasks: 
  - name: "say hi from amazon servers"
    debug:
      msg: "hi"
  
  roles:
  - jenkins


