---
- name: Create VPC with Private and Public Subnets in 2 AZs
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-2"
    vpc_cidr_block: "10.0.0.0/16"
    public_subnet_cidr_blocks:
      - "10.0.1.0/24"
      - "10.0.2.0/24"
    private_subnet_cidr_blocks:
      - "10.0.3.0/24"
      - "10.0.4.0/24"
  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc:
        region: "{{ aws_region }}"
        state: present
        cidr_block: "{{ vpc_cidr_block }}"
        resource_tags:
          Name: "my-vpc"
      register: vpc

    - name: Create Internet Gateway
      amazon.aws.ec2_internet_gateway:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc.vpc.id }}"
        state: present
        resource_tags:
          Name: "my-internet-gateway"
      register: igw

    - name: Attach Internet Gateway to VPC
      amazon.aws.ec2_vpc_igw:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc.vpc.id }}"
        internet_gateway_id: "{{ igw.internet_gateway.id }}"
        state: present

    - name: Create Public Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ aws_region }}"
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ item }}"
        availability_zone: "{{ ['us-west-2a', 'us-west-2b'][(item_index-1) % 2] }}"
        resource_tags:
          Name: "public-subnet-{{ item_index }}"
          Type: "public"
      loop: "{{ public_subnet_cidr_blocks }}"
      register: public_subnets

    - name: Create Private Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ aws_region }}"
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ item }}"
        availability_zone: "{{ ['us-west-2a', 'us-west-2b'][(item_index-1) % 2] }}"
        resource_tags:
          Name: "private-subnet-{{ item_index }}"
          Type: "private"
      loop: "{{ private_subnet_cidr_blocks }}"
      register: private_subnets

    - name: Output VPC Information
      debug:
        var: vpc

    - name: Output Public Subnets Information
      debug:
        var: public_subnets

    - name: Output Private Subnets Information
      debug:
        var: private_subnets
