---
- name: Install Java
  shell: sudo amazon-linux-extras install java-openjdk11 -y

- name: Add the Jenkins repo
  shell: sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo

- name: Import a key file from Jenkins-CI to enable installation from the package
  shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: upgrade all packages
  yum: name=* state=latest

- name: install java 
  shell: sudo amazon-linux-extras install java-openjdk11 -y
# - name: Add Jenkins repository
#   yum_repository:
#     name: jenkins
#     description: Add Jenkins repository
#     baseurl: https://pkg.jenkins.io/redhat-stable/
#     gpgcheck: yes
#     gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
#     enabled: yes
#     state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
