---
- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    baseurl: https://pkg.jenkins.io/redhat-stable/
    gpgcheck: yes
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    enabled: yes
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
